bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 50
              time: 10
              unit: seconds

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml