ALTER TABLE guest
ADD first_name VARCHAR(255),
ADD last_name VARCHAR(255),
ADD email VARCHAR(255),
ADD password VARCHAR(255),
ADD locked BIT(1),
ADD enabled BIT(1),
ADD application_user_role VARCHAR(255),
ADD street VARCHAR(255),
ADD city VARCHAR(255),
ADD state VARCHAR(255),
ADD country VARCHAR(255),
ADD zipcode VARCHAR(255);
