CREATE TABLE confirmation_token (
    CONFIRMATION_TOKEN_ID INT AUTO_INCREMENT NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    GUEST_ID INT NOT NULL,
    PRIMARY KEY (CONFIRMATION_TOKEN_ID),
    FOREIGN KEY (GUEST_ID)
        REFERENCES guest (GUEST_ID)
        ON DELETE CASCADE
)