ALTER TABLE employee
ADD LOCKED BIT(1),
ADD ENABLED BIT(1),
ADD APPLICATION_USER_ROLE VARCHAR(255);

CREATE TABLE admin (
    ADMIN_ID INT AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    LOCKED BIT(1),
    ENABLED BIT(1),
    APPLICATION_USER_ROLE VARCHAR(255),
    HOTEL_ID INT NOT NULL,
    PRIMARY KEY (ADMIN_ID, HOTEL_ID),
    FOREIGN KEY (HOTEL_ID)
        REFERENCES hotel (HOTEL_ID)

)