CREATE TABLE employee (
    EMPLOYEE_ID INT AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    HOTEL_ID INT NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID, HOTEL_ID),
    FOREIGN KEY (HOTEL_ID)
        REFERENCES hotel (HOTEL_ID)
);