CREATE TABLE availability_cart (
    AVAILABILITY_CART_ID INT AUTO_INCREMENT NOT NULL,
    GUEST_ID INT NOT NULL,
    PRIMARY KEY (AVAILABILITY_CART_ID),
        FOREIGN KEY (GUEST_ID)
                REFERENCES guest (GUEST_ID)
                ON DELETE CASCADE
);


CREATE TABLE availability (
    AVAILABILITY_ID INT AUTO_INCREMENT NOT NULL,
    CONFIRMED TINYINT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    HOTEL_NAME VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    GRADE VARCHAR(45) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    ROOM_ID INT UNSIGNED NOT NULL,
    ROOM_TYPE VARCHAR(45) NOT NULL,
    FROM_DATE DATETIME NOT NULL,
    TO_DATE DATETIME NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    AVAILABILITY_CART_ID INT,
    PRIMARY KEY (AVAILABILITY_ID),
        FOREIGN KEY (AVAILABILITY_CART_ID)
            REFERENCES availability_cart (AVAILABILITY_CART_ID)
            ON DELETE CASCADE
)


