CREATE TABLE image (
    IMAGE_ID INT AUTO_INCREMENT NOT NULL,
    IMAGE_LINK VARCHAR(255) NOT NULL,
    HOTEL_ID INT NOT NULL,
    PRIMARY KEY (IMAGE_ID),
    FOREIGN KEY (HOTEL_ID)
    REFERENCES hotel (HOTEL_ID)
        ON DELETE CASCADE
);

ALTER TABLE room
ADD DESCRIPTION VARCHAR(255);