DROP TABLE room_reservation;

CREATE TABLE reservation_arrangement (
    RESERVATION_ARRANGEMENT_ID INT AUTO_INCREMENT NOT NULL,
    PARTY_SIZE INT NOT NULL,
    NUMBER_OF_ROOMS INT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CONFIRMED BIT,
    PRICE DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (RESERVATION_ARRANGEMENT_ID)
);

ALTER TABLE reservation
ADD COLUMN RESERVATION_ARRANGEMENT_ID INT NOT NULL;

ALTER TABLE reservation
ADD FOREIGN KEY (RESERVATION_ARRANGEMENT_ID) REFERENCES reservation_arrangement(RESERVATION_ARRANGEMENT_ID);