ALTER TABLE reservation ADD COLUMN HOTEL_ID INT NOT NULL;
ALTER TABLE reservation ADD COLUMN CITY VARCHAR(255) NOT NULL;
ALTER TABLE reservation ADD COLUMN GRADE VARCHAR(45) NOT NULL;
ALTER TABLE reservation ADD COLUMN IMAGE VARCHAR(255) NOT NULL;
ALTER TABLE reservation ADD COLUMN ROOM_TYPE VARCHAR(45) NOT NULL;
ALTER TABLE reservation DROP COLUMN EMAIL;