CREATE TABLE room_group (
    ROOM_GROUP_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ROOM_GROUP_ID)
);

ALTER TABLE room DROP COLUMN ROOM_GROUP;

ALTER TABLE room ADD COLUMN ROOM_GROUP_ID INT NOT NULL;

ALTER TABLE room
ADD CONSTRAINT ROOM_GROUP_ID
FOREIGN KEY (ROOM_GROUP_ID) REFERENCES room_group(ROOM_GROUP_ID);