CREATE TABLE checkout_payment (
    PAYMENT_ID INT NOT NULL AUTO_INCREMENT,
    PAYMENT_INTENT_ID VARCHAR(255) UNIQUE,
    FEATURE_REQUEST VARCHAR(255),
    EMAIL VARCHAR(255),
    CURRENCY VARCHAR(255) NOT NULL,
    AMOUNT INT NOT NULL,
    PAYMENT_TYPE VARCHAR(255) NOT NULL,
    RESERVATION_ARRANGEMENT_ID INT NOT NULL,
    PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT RESERVATION_ARRANGEMENT_ID
    FOREIGN KEY (RESERVATION_ARRANGEMENT_ID) REFERENCES RESERVATION_ARRANGEMENT (RESERVATION_ARRANGEMENT_ID)
);

