CREATE TABLE IF NOT EXISTS hotel (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    STREET VARCHAR(150),
    CITY VARCHAR(45),
    STATE VARCHAR(150),
    COUNTRY VARCHAR(45),
    ZIPCODE VARCHAR(45),
    PHONE_NUMBER VARCHAR(15),
    EMAIL VARCHAR(150),
    GRADE VARCHAR(45)
)

CREATE TABLE IF NOT EXISTS room (
    ID INT AUTO_INCREMENT NOT NULL,
    NUMBER INT NOT NULL,
    ROOM_TYPE VARCHAR(45) NOT NULL,
    HOTEL_ID INT NOT NULL,
    PRIMARY KEY(ID, HOTEL_ID),
    FOREIGN KEY (HOTEL_ID)
        REFERENCES hotel (ID)
        ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS guest (
    GUESTID INT AUTO_INCREMENT PRIMARY KEY NOT NULL
)

CREATE TABLE IF NOT EXISTS opening_times (
    ID INT AUTO_INCREMENT NOT NULL,
    DAY_OF_WEEK VARCHAR(45),
    FROM VARCHAR(45),
    TO VARCHAR(45),
    HOTEL_ID INT NOT NULL,
    PRIMARY KEY (ID, HOTEL_ID),
    FOREIGN KEY (HOTEL_ID)
        REFERENCES hotel (ID)
        ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS reservation (
    ID INT AUTO_INCREMENT NOT NULL,
    PARTY_SIZE INT,
    FROM DATETIME,
    TO DATETIME,
    GUESTID INT NOT NULL,
    PRIMARY KEY(ID, GUESTID),
    FOREIGN KEY (GUESTID)
        REFERENCES guest (GUESTID)
)

CREATE TABLE IF NOT EXISTS room_reservation (
    ID INT NOT NULL,
    RESERVATION INT,
    RESERVATION_ID INT NOT NULL,
    ROOM_ID INT NOT NULL,
    PRIMARY KEY (ID, RESERVATION),
    FOREIGN KEY (RESERVATION_ID)
        REFERENCES reservation (ID),
    FOREIGN KEY (ROOM_ID)
        REFERENCES room (ID)
)