CREATE TABLE IF NOT EXISTS hotel (
    HOTEL_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    STREET VARCHAR(150),
    CITY VARCHAR(45),
    STATE VARCHAR(150),
    COUNTRY VARCHAR(45),
    ZIPCODE VARCHAR(45),
    PHONE_NUMBER VARCHAR(15),
    EMAIL VARCHAR(150),
    GRADE VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS room (
    ROOM_ID INT AUTO_INCREMENT NOT NULL,
    NUMBER INT NOT NULL,
    ROOM_TYPE VARCHAR(45) NOT NULL,
    HOTEL_ID INT NOT NULL,
    PRIMARY KEY(ROOM_ID, HOTEL_ID),
    FOREIGN KEY (HOTEL_ID)
        REFERENCES hotel (HOTEL_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS guest (
    GUEST_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS opening_times (
    OPENING_TIMES_ID INT AUTO_INCREMENT NOT NULL,
    DAY_OF_WEEK VARCHAR(45),
    FROM_DATA VARCHAR(45),
    TO_DATA VARCHAR(45),
    HOTEL_ID INT NOT NULL,
    PRIMARY KEY (OPENING_TIMES_ID, HOTEL_ID),
    FOREIGN KEY (HOTEL_ID)
        REFERENCES hotel (HOTEL_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reservation (
    RESERVATION_ID INT AUTO_INCREMENT NOT NULL,
    PARTY_SIZE INT,
    FROM_DATA DATETIME,
    TO_DATA DATETIME,
    GUEST_ID INT NOT NULL,
    PRIMARY KEY(RESERVATION_ID, GUEST_ID),
    FOREIGN KEY (GUEST_ID)
        REFERENCES guest (GUEST_ID)
);

CREATE TABLE IF NOT EXISTS room_reservation (
    RESERVATION_ID INT NOT NULL,
    ROOM_ID INT NOT NULL,
    PRIMARY KEY (RESERVATION_ID, ROOM_ID),
    FOREIGN KEY (RESERVATION_ID)
        REFERENCES reservation (RESERVATION_ID),
    FOREIGN KEY (ROOM_ID)
        REFERENCES room (ROOM_ID)
);